### ISSUE TITLE
Cannot connect to APNs: Connection has already been opened and must be closed

### ISSUE THREAD

**Issue by lucadegasperi** [laravel-notification-channels/apn#10]
I'm getting this error message and by digging further it looks like this package doesn't allow to send notifications to multiple users at once. If i send a notification to a single user no problem is encountered, when I want to send multiple notifications to multiple users at once, it fails.

**Comment by barryvdh** [comment]
Fixed with #11?

**Comment by mmehdibalouchi** [comment]
@barryvdh 
Hii :)
I still have this error
`ZendService\Apple\Exception\RuntimeException: Connection has already been opened and must be closed in`

**Comment by fureszk** [comment]
Still having this error.
